blank_issues_enabled: false
contact_links:
  - name: smack.new related issues
    url: https://github.com/stackblitz/smack.new/issues/new/choose
    about: Report issues related to smack.new (not smack.sh)
  - name: Chat
    url: https://thinktank.ottomator.ai
    about: Ask questions and discuss with other smack.sh users.
